# -*- coding: utf-8 -*-
"""Global Debt Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQmJcwwB_BXh-Fvo7-v6cb4DFkz7O7ep
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd

import chardet

with open("central_government_debt.csv", "rb") as f:
    encoding = chardet.detect(f.read())["encoding"]

df = pd.read_csv("central_government_debt.csv", encoding=encoding)

df.head()

df.info()

df.describe()

df.describe(include = "object")

df.head(10)

df.shape

2022 -1950

df.columns

df.tail()

df.tail(10)

df.tail(50)

df.tail(70)

df.tail(60)

df.tail(65)

df.tail(63)

df.tail(62)

df.tail(61)

df.tail(60)

df.head(60)

df[["country_name", "2020", "2021", "2022"]]

df[["country_name", "2020", "2021", "2022"]].describe()

df[["country_name", "2020", "2021", "2022"]].max()

df[df["country_name"] == "India"].loc[:,"2010":]

df[df["country_name"] == "India"].loc[:,"2000":"2010"]

df[df["country_name"] == "India"].loc[:,"1990":"2000"]

df.rename({"country_name" : "country"}, inplace = True)

df

df.rename({"country_name" : "country"}, axis = 1)

df

df.rename({"country_name" : "country"}, axis = 1, inplace = "True")

df

india = df[df.country == "India"]
india

print(type(india))

india.loc[:,"1950": "1960"]

df.set_index("country")

for i in range(1950,2013, 11):
  print(india.loc[:, str(i): str(i + 10)])
  print()

india.loc[:, "2016":]

india.loc[:, "1950": "1960"]

india.loc[:, "1961": "1970"]

india.loc[:, "1971": "1980"]

india.loc[:, "1981": "1990"]

india.loc[:, "1991": "2000"]

india.loc[:, "2000": "2010"]

india.loc[:, "2011": "2022"]

india_column_wise = india.T
india_column_wise.head(60)

import matplotlib.pyplot as plt
import seaborn as sns

india = india.transpose()
india.columns = ["value"]

india

india.info

india.describe()

india.loc["country"]

india.index

india = india.drop(india.index[[0, 1]],axis = 0)
india

plt.figure(figsize = (12, 13))
plt.plot(india)
plt.xticks(rotation = 90)

plt.xlabel("year")
plt.ylabel("year")
plt.title("India")
plt.show()

plt.figure(figsize = (12, 6))
plt.plot(india, "r")
plt.xticks(rotation = 90)

plt.xlabel("year")
plt.ylabel("year")
plt.title("India")
plt.show()

df.head()

china = df.loc[df.country == "China"]
df.tail(60)

usa = df.loc[df.country == "United States"]
usa

pakistan = df.loc[df.country == "Pakistan"]
pakistan

bangla = df.loc[df.country == "Bangladesh"]
bangla

usa = usa.transpose()

usa

usa.drop(["country", "indicator_name"] , axis = 0, inplace = True)

usa.rename({164 : "value"}, axis = 1, inplace = True )

usa.columns

usa

plt.figure(figsize = (14, 7))
plt.plot(usa)

plt.xticks(rotation = 90)
plt.legend(["usa"])

plt.figure(figsize = (14, 7))
plt.plot(usa)
plt.plot(india, color = "purple")
plt.xticks(rotation = 90)
plt.xlabel("year")
plt.ylabel("value")
plt.legend(["usa", "India"])

bangla

bangla = bangla.transpose()

bangla

bangla.drop(["country", "indicator_name"], axis = 0, inplace = True)
bangla.rename({12: "value"}, axis = 1, inplace = True)
bangla

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
sns.lineplot(bangla)

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(bangla, color = "green")
plt.plot(india, color = "orange")

plt.legend(["bangla", "ind"])
plt.show()

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(bangla, color = "green")
plt.plot(india, color = "orange")
plt.plot (usa, color = "pink", alpha = 1)
plt.legend(["bangla", "ind", "us"])
plt.show()

pakistan

pakistan = pakistan.transpose()

pakistan

pakistan.drop(["country", "indicator_name"], axis = 0, inplace = True)
pakistan.rename({117 : "value"}, axis = 1, inplace = True)

pakistan

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
sns.lineplot(pakistan)

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(pakistan, color = "green")
plt.plot(india, color = "orange")

plt.legend(["pakistan", "ind", "us"])
plt.show()

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(bangla, color = "green")
plt.plot(india, color = "orange")
plt.plot (usa, color = "pink", alpha = 1)
sns.lineplot(pakistan)
plt.legend(["bangla", "ind", "us", "pakistan"])
plt.show()

iran = df[df.country == "Iran"]

israel = df[df.country == "Israel"]

ukraine = df[df.country == "Ukraine"]

ukraine

rus = df[df.country == "Russia"]
rus

df.tail(60)

rus = df[df.country == "Russian Federation"]
russ = rus

taiwan = df[df.country == "Taiwan Province of China"]

taiwan

uk = df[df.country == "United Kingdom"]
uk

france = df[df.country == "France"]
france

singapore = df[df.country == "Singapore"]
singapore

singapore = singapore.transpose()
russ = russ.transpose()
france = france.transpose()
ukraine = ukraine.transpose()
iran = iran.transpose()
israel = israel.transpose()
taiwan = taiwan.transpose()
uk = uk.transpose()

a = [
russ,
france,
ukraine,
iran,
israel ,
taiwan,
uk ]
a

france.columns = ["value"]
france

a

def clean(x):

  x.drop(["country", "indicator_name"], axis = 0, inplace = True)

  x.columns = ["value"]
a

russ
plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(russ)

france

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(france)
plt.title("France")

ukraine

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(ukraine)
plt.title("Ukraine")

iran

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(iran)
plt.title("Iran")

uk
uk.dropna()

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(uk)
plt.title("uk")

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(israel)
plt.title("Israel")

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(taiwan)
plt.title("Taiwan")

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(uk, label = "uk")
plt.plot(france, label = "france")
plt.plot(russ, label = "russ")
plt.plot(india, label = "Ind")
plt.legend()

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(uk, label = "uk")
plt.plot(france, label = "france")
plt.plot(russ, label = "russ")
plt.plot(india, label = "Ind")
plt.plot(israel, label = "Israel")
plt.legend()

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(uk, label = "uk")
plt.plot(france, label = "france")
plt.plot(russ, label = "russ")
plt.plot(india, label = "Ind")
plt.legend()

df

plt.figure(figsize = (14, 7))
plt.xticks(rotation = 90)
plt.plot(russ, color = "green")
plt.plot(india, color = "orange")
plt.plot (ukraine, color = "pink", alpha = 1)
sns.lineplot(pakistan)
plt.legend(["russ", "ind", "ukraine", "pakistan"])
plt.show()

df

df[df.country_name.str.startswith("The")]

df.loc[df.country_name.str.contains("hina")].dropna()

df = pd.read_csv("central_government_debt.csv", encoding= "ISO-8859-1")
df.rename({"country_name" : "country"}, axis = 0, inplace = True)
result_df = df.T
result_df.drop("indicator_name", axis = 0, inplace = True)
result_df

result_df.columns

result_df.loc["country_name"]

result_df.columns = result_df.loc["country_name"]
result_df

result_df.drop("country_name", axis = 0, inplace = True)

result_df

plt.figure(figsize = (16, 8))
sns.lineplot(result_df)

plt.figure(figsize = (16, 16))
plt.xticks(rotation = 90)
sns.lineplot(result_df)

df2 = pd.read_csv("/content/drive/MyDrive/ML project/general_government_debt.csv")
df2

df2.info()

df2.describe()

df2.describe(include = "object")

df2.duplicated()

import numpy as np

np.all(df2.duplicated())

df2.loc[df2.duplicated()]

df2.duplicated().sum()

df2.head(50)

df2.tail(50)

df2.drop("indicator_name", axis = 1, inplace = True)
df2

df2.loc[82]

us = df2.loc[82].transpose()
us



china = df2[df2.country_name == "China, People's Republic of"]

china

china = china.T
china

#china.drop("country_name", axis = 0, inplace = True)
china.columns
china

import seaborn as sns

sns.kdeplot(china)

import matplotlib.pyplot as plt

plt.figure(figsize = (14, 6))
plt.plot(china, "r")
plt.xlabel("China")
plt.grid( )

df2.head(30)

df2.tail(30)

us = df2[df2.country_name == "United States"]
us

us = us.T
us

us.drop('country_name', axis = 0, inplace = True)
us.columns = ["value"]

sns.kdeplot(us)

import matplotlib.pyplot as plt

plt.figure(figsize = (14, 6))
plt.plot(china, "r", label = "China")
plt.plot(us, label = "US")
plt.legend()
plt.xlabel("year")
plt.ylabel("value")
plt.xticks(rotation = 90)
plt.grid( )

import matplotlib.pyplot as plt

plt.figure(figsize = (14, 6))
plt.plot(us, color = "purple")
plt.title("US")
plt.xticks(rotation = 90)
plt.grid( )

